name: Feedback
description: Share your thoughts
title: "[FEEDBACK]: "
body:
  - type: textarea
    id: extra-notes
    attributes:
      label: "### Additional Notes"
      description: "Anything else you'd like to add?"
      placeholder: "Optional"
    validations:
      required: false
